---
version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: '/'
    groups:
      github:
        patterns:
          - 'actions/*'
          - 'github/*'
    schedule:
      interval: 'weekly'
  - package-ecosystem: 'composer'
    directory: '/'
    schedule:
      interval: 'weekly'
