name: Common Setup

on:
  workflow_call:
    inputs:
      php-version:
        required: true
        type: string
      cache-key-suffix:
        required: true
        type: string

jobs:
  setup:
    runs-on: ubuntu-22.04

    steps:
    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: mbstring, pdo, pdo_mysql
        ini-values: |
          memory_limit=512M
        coverage: none

    - name: Get Composer Cache
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ inputs.cache-key-suffix }}
        restore-keys: ${{ runner.os }}-composer-${{ inputs.cache-key-suffix }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest