name: Run PhpSpec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  phpspec:
    runs-on: ubuntu-22.04

    strategy:
      matrix:
        php-version: ['7.0', '7.4', '8.0', '8.3']

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Common Setup
      uses: ./.github/workflows/common-setup.yml
      with:
        php-version: ${{ matrix.php-version }}
        cache-key-suffix: ${{ matrix.php-version }}

    - name: Run PhpSpec
      run: vendor/bin/phpspec run