name: Run PhpSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  phpspec:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4', '8.0', '8.1']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        ini-values: |
          memory_limit=512M
        coverage: none

    - name: Get Composer Cache
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: ~/.composer/cache
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}-${{ matrix.php-version }}
        restore-keys: ${{ runner.os }}-composer-${{ matrix.php-version }}

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run PhpSpec
      run: vendor/bin/phpspec run
